### ISSUE TITLE
Keeping getting lat needs to be defined.

### ISSUE THREAD

**Issue by gurubagawan** [nathanpdaniel/uber-api#4]
To start off, I copied and pasted the sample code. No matter what I do I get the issue that lat needs to be defined. Is there a fix for this?

**Comment by nathanpdaniel** [comment]
@gurubagawan The fix is actually in the documentation and example code. There were changes merged updating the library which did not make it to the example code.
The proper usage now would be to pass in an object with `lat` and `lng` properties equal to your latitude and longitude:
```
Uber.getProducts({lat, lng}, function(error, response) {
  if (error) {
    console.log(error);
  } else {
    console.log(response);
  }
});
```
Or:
```
Uber.getProducts({lat, lng}).then(function(response){
  console.log(response);
}, function(error){
  console.error(response);
});
```
